runtime: python37

instance_class: F2
automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 0
  max_instances: 3
  min_pending_latency: 30ms
  max_pending_latency: automatic
  max_concurrent_requests: 20

env_variables:
    ENV: GCP

handlers:
- url: /static
  static_dir: public